services:
  - type: web
    name: nexus-news-api
    env: python
    buildCommand: pip install -r requirements.txt && python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab'); nltk.download('stopwords')"
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NEWSAPI_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HUGGINGFACE_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-news-db
          property: connectionString

databases:
  - name: nexus-news-db
    plan: free